// 中国护照签证数据（2026年5月最新，199个国家/地区）
// policy: free=免签, arrival=落地签, evisa=电子签, visa=需签证
const VISA_DATA = {
"CN":{cn:"中国",en:"China",flag:"🇨🇳",code:"CN",lat:35,lng:105,policy:"home",duration:"—",fee:"—",process:"—",validity:"—",requirements:"本国",tips:"自己家"},
"JP":{cn:"日本",en:"Japan",flag:"🇯🇵",code:"JP",lat:36,lng:138,policy:"visa",duration:"—",fee:"200元",process:"5-7工作日",validity:"3个月单次",requirements:"护照、照片、在职证明、银行流水、行程单",tips:"需提前办理"},
"KR":{cn:"韩国",en:"South Korea",flag:"🇰🇷",code:"KR",lat:36,lng:128,policy:"visa",duration:"—",fee:"260元",process:"5-7工作日",validity:"3个月单次",requirements:"护照、照片、在职证明、银行流水",tips:"济州岛免签30天"},
"KP":{cn:"朝鲜",en:"North Korea",flag:"🇰🇵",code:"KP",lat:40,lng:127,policy:"visa",duration:"—",fee:"—",process:"需跟团",validity:"—",requirements:"必须跟团",tips:"只能通过丹东等口岸跟团"},
"MN":{cn:"蒙古",en:"Mongolia",flag:"🇲🇳",code:"MN",lat:47,lng:104,policy:"visa",duration:"—",fee:"400元",process:"3-5工作日",validity:"30天",requirements:"护照、照片、邀请函",tips:"从二连浩特或满洲里可到"},
"TH":{cn:"泰国",en:"Thailand",flag:"🇹🇭",code:"TH",lat:15,lng:101,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"—",requirements:"护照、往返机票",tips:"互免签证！东南亚最热门"},
"VN":{cn:"越南",en:"Vietnam",flag:"🇻🇳",code:"VN",lat:16,lng:108,policy:"evisa",duration:"90天",fee:"25美元",process:"3工作日",validity:"90天",requirements:"护照、照片、网上申请",tips:"电子签很方便"},
"MY":{cn:"马来西亚",en:"Malaysia",flag:"🇲🇾",code:"MY",lat:4,lng:102,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"—",requirements:"护照、往返机票",tips:"互免签证！美食天堂"},
"SG":{cn:"新加坡",en:"Singapore",flag:"🇸🇬",code:"SG",lat:1.3,lng:104,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"—",requirements:"护照、需提前填SGArrival Card",tips:"互免签证！转机枢纽"},
"ID":{cn:"印度尼西亚",en:"Indonesia",flag:"🇮🇩",code:"ID",lat:-5,lng:120,policy:"arrival",duration:"30天",fee:"约250元",process:"到达办理",validity:"30天",requirements:"护照、往返机票",tips:"巴厘岛很热门"},
"PH":{cn:"菲律宾",en:"Philippines",flag:"🇵🇭",code:"PH",lat:13,lng:122,policy:"free",duration:"14天",fee:"免费",process:"—",validity:"14天",requirements:"护照",tips:"2026年1月起免签14天"},
"MM":{cn:"缅甸",en:"Myanmar",flag:"🇲🇲",code:"MM",lat:20,lng:96,policy:"evisa",duration:"28天",fee:"50美元",process:"3工作日",validity:"28天",requirements:"护照、照片、网上申请",tips:"局势不稳定"},
"LA":{cn:"老挝",en:"Laos",flag:"🇱🇦",code:"LA",lat:18,lng:103,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照、照片",tips:"从云南磨憨口岸可到"},
"KH":{cn:"柬埔寨",en:"Cambodia",flag:"🇰🇭",code:"KH",lat:12,lng:105,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照、照片",tips:"吴哥窟必去"},
"BN":{cn:"文莱",en:"Brunei",flag:"🇧🇳",code:"BN",lat:4.5,lng:114.7,policy:"free",duration:"14天",fee:"免费",process:"—",validity:"14天",requirements:"护照",tips:"单方面免签14天"},
"TL":{cn:"东帝汶",en:"East Timor",flag:"🇹🇱",code:"TL",lat:-8.8,lng:126,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照、往返机票",tips:"从巴厘岛飞最方便"},
"PK":{cn:"巴基斯坦",en:"Pakistan",flag:"🇵🇰",code:"PK",lat:30,lng:70,policy:"evisa",duration:"30天",fee:"约200元",process:"3-5工作日",validity:"30天",requirements:"护照、照片、网上申请",tips:"安全形势需关注"},
"BD":{cn:"孟加拉国",en:"Bangladesh",flag:"🇧🇩",code:"BD",lat:24,lng:90,policy:"arrival",duration:"30天",fee:"约350元",process:"到达办理",validity:"30天",requirements:"护照、照片、往返机票",tips:"达卡较拥挤"},
"IN":{cn:"印度",en:"India",flag:"🇮🇳",code:"IN",lat:20,lng:79,policy:"evisa",duration:"30天",fee:"25美元",process:"3-5工作日",validity:"30天",requirements:"护照、照片、网上申请",tips:"电子签很方便"},
"NP":{cn:"尼泊尔",en:"Nepal",flag:"🇳🇵",code:"NP",lat:28,lng:84,policy:"arrival",duration:"15/30/90天",fee:"约200-700元",process:"到达办理",validity:"15-90天",requirements:"护照、照片",tips:"从拉萨可陆路进入"},
"LK":{cn:"斯里兰卡",en:"Sri Lanka",flag:"🇱🇰",code:"LK",lat:7,lng:81,policy:"evisa",duration:"30天",fee:"免费",process:"1-2工作日",validity:"30天",requirements:"护照、网上申请",tips:"ETA免费办理"},
"MV":{cn:"马尔代夫",en:"Maldives",flag:"🇲🇻",code:"MV",lat:3.2,lng:73,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照、酒店预订、往返机票",tips:"互免签证！蜜月圣地"},
"BT":{cn:"不丹",en:"Bhutan",flag:"🇧🇹",code:"BT",lat:27.5,lng:90.5,policy:"visa",duration:"—",fee:"每日约1500元",process:"需提前申请",validity:"按行程",requirements:"必须通过旅行社",tips:"全球最贵旅游国之一"},
"AF":{cn:"阿富汗",en:"Afghanistan",flag:"🇦🇫",code:"AF",lat:33,lng:65,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"安全形势严峻，不建议前往"},
"IR":{cn:"伊朗",en:"Iran",flag:"🇮🇷",code:"IR",lat:32,lng:53,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！物价极低，波斯文化值得体验"},
"IQ":{cn:"伊拉克",en:"Iraq",flag:"🇮🇶",code:"IQ",lat:33,lng:44,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"安全形势不稳定"},
"SA":{cn:"沙特阿拉伯",en:"Saudi Arabia",flag:"🇸🇦",code:"SA",lat:24,lng:45,policy:"evisa",duration:"90天",fee:"约500元",process:"即时",validity:"1年多次",requirements:"护照、网上申请",tips:"电子签很方便"},
"AE":{cn:"阿联酋",en:"UAE",flag:"🇦🇪",code:"AE",lat:24,lng:54,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！迪拜转机枢纽"},
"QA":{cn:"卡塔尔",en:"Qatar",flag:"🇶🇦",code:"QA",lat:25.3,lng:51.5,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！多哈转机枢纽"},
"KW":{cn:"科威特",en:"Kuwait",flag:"🇰🇼",code:"KW",lat:29.5,lng:48,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"商务签证为主"},
"BH":{cn:"巴林",en:"Bahrain",flag:"🇧🇭",code:"BH",lat:26,lng:50.5,policy:"evisa",duration:"14天",fee:"约300元",process:"即时",validity:"14天",requirements:"护照、网上申请",tips:"电子签很方便"},
"OM":{cn:"阿曼",en:"Oman",flag:"🇴🇲",code:"OM",lat:21,lng:57,policy:"evisa",duration:"30天",fee:"约200元",process:"即时",validity:"30天",requirements:"护照、网上申请",tips:"自然风光很美"},
"YE":{cn:"也门",en:"Yemen",flag:"🇾🇪",code:"YE",lat:15.5,lng:48,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"战乱地区，不建议前往"},
"JO":{cn:"约旦",en:"Jordan",flag:"🇯🇴",code:"JO",lat:31,lng:36,policy:"arrival",duration:"30天",fee:"约350元",process:"到达办理",validity:"30天",requirements:"护照",tips:"佩特拉必去，买Jordan Pass"},
"LB":{cn:"黎巴嫩",en:"Lebanon",flag:"🇱🇧",code:"LB",lat:33.9,lng:35.5,policy:"arrival",duration:"30天",fee:"免费",process:"到达办理",validity:"30天",requirements:"护照",tips:"局势需关注"},
"SY":{cn:"叙利亚",en:"Syria",flag:"🇸🇾",code:"SY",lat:35,lng:38,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"战乱地区，不建议前往"},
"IL":{cn:"以色列",en:"Israel",flag:"🇮🇱",code:"IL",lat:31.5,lng:35,policy:"visa",duration:"—",fee:"约150元",process:"5-10工作日",validity:"3个月",requirements:"护照、照片、行程单",tips:"入境记录影响去某些阿拉伯国家"},
"TR":{cn:"土耳其",en:"Turkey",flag:"🇹🇷",code:"TR",lat:39,lng:35,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"180天",requirements:"护照",tips:"2025年起免签90天！亚欧枢纽"},
"CY":{cn:"塞浦路斯",en:"Cyprus",flag:"🇨🇾",code:"CY",lat:35,lng:33,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需申根签证",tips:"已加入申根区"},
"GE":{cn:"格鲁吉亚",en:"Georgia",flag:"🇬🇪",code:"GE",lat:42,lng:43.5,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！户外徒步天堂"},
"AM":{cn:"亚美尼亚",en:"Armenia",flag:"🇦🇲",code:"AM",lat:40,lng:45,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"180天",requirements:"护照",tips:"互免签证！历史悠久"},
"AZ":{cn:"阿塞拜疆",en:"Azerbaijan",flag:"🇦🇿",code:"AZ",lat:40.5,lng:47.5,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！巴库很现代"},
"KZ":{cn:"哈萨克斯坦",en:"Kazakhstan",flag:"🇰🇿",code:"KZ",lat:48,lng:67,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！中亚最大国家"},
"UZ":{cn:"乌兹别克斯坦",en:"Uzbekistan",flag:"🇺🇿",code:"UZ",lat:41,lng:64,policy:"free",duration:"10天",fee:"免费",process:"—",validity:"10天",requirements:"护照",tips:"互免签证！撒马尔罕，注意只10天！"},
"KG":{cn:"吉尔吉斯斯坦",en:"Kyrgyzstan",flag:"🇰🇬",code:"KG",lat:41,lng:75,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！伊塞克湖很美"},
"TJ":{cn:"塔吉克斯坦",en:"Tajikistan",flag:"🇹🇯",code:"TJ",lat:39,lng:71,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！帕米尔公路"},
"TM":{cn:"土库曼斯坦",en:"Turkmenistan",flag:"🇹🇲",code:"TM",lat:40,lng:60,policy:"visa",duration:"—",fee:"—",process:"需邀请函",validity:"5天过境",requirements:"邀请函、旅行社担保",tips:"最难签证国之一"},
"RU":{cn:"俄罗斯",en:"Russia",flag:"🇷🇺",code:"RU",lat:60,lng:100,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"至2026.9.14",requirements:"护照",tips:"临时互免至2026.9.14！西伯利亚铁路必体验"},
"BY":{cn:"白俄罗斯",en:"Belarus",flag:"🇧🇾",code:"BY",lat:53,lng:28,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证，入境方式有限制"},
"UA":{cn:"乌克兰",en:"Ukraine",flag:"🇺🇦",code:"UA",lat:49,lng:32,policy:"evisa",duration:"—",fee:"约300元",process:"3-5工作日",validity:"30天",requirements:"护照、网上申请",tips:"2025年恢复电子签"},
"PL":{cn:"波兰",en:"Poland",flag:"🇵🇱",code:"PL",lat:52,lng:20,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"DE":{cn:"德国",en:"Germany",flag:"🇩🇪",code:"DE",lat:51,lng:10,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"FR":{cn:"法国",en:"France",flag:"🇫🇷",code:"FR",lat:46,lng:2,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"IT":{cn:"意大利",en:"Italy",flag:"🇮🇹",code:"IT",lat:42,lng:12,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"ES":{cn:"西班牙",en:"Spain",flag:"🇪🇸",code:"ES",lat:40,lng:-4,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"PT":{cn:"葡萄牙",en:"Portugal",flag:"🇵🇹",code:"PT",lat:39,lng:-8,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"GB":{cn:"英国",en:"United Kingdom",flag:"🇬🇧",code:"GB",lat:54,lng:-2,policy:"visa",duration:"—",fee:"约900元",process:"15工作日",validity:"2年多次",requirements:"护照、照片、在职证明、银行流水",tips:"不在申根区内"},
"IE":{cn:"爱尔兰",en:"Ireland",flag:"🇮🇪",code:"IE",lat:53,lng:-8,policy:"visa",duration:"—",fee:"约500元",process:"10-15工作日",validity:"按行程",requirements:"单独签证",tips:"不在申根区"},
"NL":{cn:"荷兰",en:"Netherlands",flag:"🇳🇱",code:"NL",lat:52,lng:5,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"阿姆斯特丹转机枢纽"},
"BE":{cn:"比利时",en:"Belgium",flag:"🇧🇪",code:"BE",lat:50.8,lng:4,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"CH":{cn:"瑞士",en:"Switzerland",flag:"🇨🇭",code:"CH",lat:47,lng:8,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"风景绝美"},
"AT":{cn:"奥地利",en:"Austria",flag:"🇦🇹",code:"AT",lat:47.3,lng:13.3,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"维也纳"},
"CZ":{cn:"捷克",en:"Czech Republic",flag:"🇨🇿",code:"CZ",lat:50,lng:15,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"布拉格很美"},
"SK":{cn:"斯洛伐克",en:"Slovakia",flag:"🇸🇰",code:"SK",lat:48.7,lng:19.7,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"HU":{cn:"匈牙利",en:"Hungary",flag:"🇭🇺",code:"HU",lat:47,lng:20,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"布达佩斯"},
"SI":{cn:"斯洛文尼亚",en:"Slovenia",flag:"🇸🇮",code:"SI",lat:46.1,lng:14.8,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"HR":{cn:"克罗地亚",en:"Croatia",flag:"🇭🇷",code:"HR",lat:45.2,lng:15,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"2024年起免签！"},
"BA":{cn:"波黑",en:"Bosnia and Herzegovina",flag:"🇧🇦",code:"BA",lat:44,lng:17.8,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！物价低"},
"RS":{cn:"塞尔维亚",en:"Serbia",flag:"🇷🇸",code:"RS",lat:44,lng:21,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！对中国最友好"},
"ME":{cn:"黑山",en:"Montenegro",flag:"🇲🇪",code:"ME",lat:42.5,lng:19.3,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照、酒店预订单",tips:"有条件免签"},
"AL":{cn:"阿尔巴尼亚",en:"Albania",flag:"🇦🇱",code:"AL",lat:41,lng:20,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！物价极低"},
"MK":{cn:"北马其顿",en:"North Macedonia",flag:"🇲🇰",code:"MK",lat:41.5,lng:21.7,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效申根/美/英签可免签15天",tips:"需第三国签证"},
"RO":{cn:"罗马尼亚",en:"Romania",flag:"🇷🇴",code:"RO",lat:46,lng:25,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"已加入申根区"},
"BG":{cn:"保加利亚",en:"Bulgaria",flag:"🇧🇬",code:"BG",lat:42.7,lng:25.5,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"已加入申根区"},
"GR":{cn:"希腊",en:"Greece",flag:"🇬🇷",code:"GR",lat:39,lng:22,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"爱琴海很美"},
"MT":{cn:"马耳他",en:"Malta",flag:"🇲🇹",code:"MT",lat:35.9,lng:14.5,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"SM":{cn:"圣马力诺",en:"San Marino",flag:"🇸🇲",code:"SM",lat:43.9,lng:12.5,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"需从意大利进入",tips:"互免但无机场"},
"LU":{cn:"卢森堡",en:"Luxembourg",flag:"🇱🇺",code:"LU",lat:49.8,lng:6.1,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"IS":{cn:"冰岛",en:"Iceland",flag:"🇮🇸",code:"IS",lat:65,lng:-18,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"极光壮观"},
"NO":{cn:"挪威",en:"Norway",flag:"🇳🇴",code:"NO",lat:62,lng:10,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"峡湾风光"},
"SE":{cn:"瑞典",en:"Sweden",flag:"🇸🇪",code:"SE",lat:62,lng:15,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"FI":{cn:"芬兰",en:"Finland",flag:"🇫🇮",code:"FI",lat:64,lng:26,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"圣诞老人故乡"},
"DK":{cn:"丹麦",en:"Denmark",flag:"🇩🇰",code:"DK",lat:56,lng:10,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"EE":{cn:"爱沙尼亚",en:"Estonia",flag:"🇪🇪",code:"EE",lat:59,lng:25,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"LV":{cn:"拉脱维亚",en:"Latvia",flag:"🇱🇻",code:"LV",lat:57,lng:24,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"LT":{cn:"立陶宛",en:"Lithuania",flag:"🇱🇹",code:"LT",lat:55,lng:24,policy:"visa",duration:"—",fee:"约450元",process:"7-15工作日",validity:"按行程",requirements:"申根签证",tips:"需申根签"},
"MD":{cn:"摩尔多瓦",en:"Moldova",flag:"🇲🇩",code:"MD",lat:47,lng:29,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"持有效申根签可免签90天",tips:"持申根签可免签"},
"AD":{cn:"安道尔",en:"Andorra",flag:"🇦🇩",code:"AD",lat:42.5,lng:1.5,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需申根签证",tips:"无机场无火车"},
"MC":{cn:"摩纳哥",en:"Monaco",flag:"🇲🇨",code:"MC",lat:43.7,lng:7.4,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需申根签证",tips:"需法国申根签"},
"LI":{cn:"列支敦士登",en:"Liechtenstein",flag:"🇱🇮",code:"LI",lat:47.2,lng:9.5,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需申根签证",tips:"从瑞士进入"},
"VA":{cn:"梵蒂冈",en:"Vatican City",flag:"🇻🇦",code:"VA",lat:41.9,lng:12.5,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需通过意大利进入",tips:"从罗马步行到达"},
"EG":{cn:"埃及",en:"Egypt",flag:"🇪🇬",code:"EG",lat:27,lng:30,policy:"arrival",duration:"30天",fee:"约150元",process:"到达办理",validity:"30天",requirements:"护照、往返机票",tips:"金字塔必看，物价低"},
"MA":{cn:"摩洛哥",en:"Morocco",flag:"🇲🇦",code:"MA",lat:32,lng:-5,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！撒哈拉沙漠"},
"TN":{cn:"突尼斯",en:"Tunisia",flag:"🇹🇳",code:"TN",lat:34,lng:9,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！迦太基遗址"},
"DZ":{cn:"阿尔及利亚",en:"Algeria",flag:"🇩🇿",code:"DZ",lat:28,lng:2,policy:"visa",duration:"—",fee:"—",process:"较复杂",validity:"—",requirements:"邀请函、酒店预订单",tips:"签证较难"},
"LY":{cn:"利比亚",en:"Libya",flag:"🇱🇾",code:"LY",lat:27,lng:17,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"邀请函",tips:"局势不稳定，不建议前往"},
"SD":{cn:"苏丹",en:"Sudan",flag:"🇸🇩",code:"SD",lat:15.5,lng:32.5,policy:"visa",duration:"—",fee:"约400元",process:"需提前办理",validity:"—",requirements:"护照、邀请函",tips:"局势不稳定，签证较难"},
"SS":{cn:"南苏丹",en:"South Sudan",flag:"🇸🇸",code:"SS",lat:7,lng:30,policy:"arrival",duration:"—",fee:"约700元",process:"到达办理",validity:"—",requirements:"护照",tips:"局势不稳定"},
"ET":{cn:"埃塞俄比亚",en:"Ethiopia",flag:"🇪🇹",code:"ET",lat:9,lng:39,policy:"evisa",duration:"30天",fee:"约350元",process:"1-3工作日",validity:"30天",requirements:"护照、网上申请",tips:"非洲航空枢纽"},
"ER":{cn:"厄立特里亚",en:"Eritrea",flag:"🇪🇷",code:"ER",lat:15,lng:39,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"邀请函",tips:"签证极难"},
"DJ":{cn:"吉布提",en:"Djibouti",flag:"🇩🇯",code:"DJ",lat:11.5,lng:43,policy:"arrival",duration:"30天",fee:"约600元",process:"到达办理",validity:"30天",requirements:"护照",tips:"非洲之角"},
"SO":{cn:"索马里",en:"Somalia",flag:"🇸🇴",code:"SO",lat:6,lng:46,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"安全形势严峻，强烈不建议前往"},
"KE":{cn:"肯尼亚",en:"Kenya",flag:"🇰🇪",code:"KE",lat:0,lng:38,policy:"evisa",duration:"90天",fee:"约350元",process:"2-3工作日",validity:"90天",requirements:"护照、网上申请",tips:"动物大迁徙必看"},
"UG":{cn:"乌干达",en:"Uganda",flag:"🇺🇬",code:"UG",lat:1,lng:32,policy:"evisa",duration:"90天",fee:"约350元",process:"2-3工作日",validity:"90天",requirements:"护照、网上申请",tips:"可看山地大猩猩"},
"TZ":{cn:"坦桑尼亚",en:"Tanzania",flag:"🇹🇿",code:"TZ",lat:-6,lng:35,policy:"arrival",duration:"90天",fee:"约350元",process:"到达办理",validity:"90天",requirements:"护照、往返机票",tips:"乞力马扎罗+桑给巴尔"},
"RW":{cn:"卢旺达",en:"Rwanda",flag:"🇷🇼",code:"RW",lat:-2,lng:29,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照",tips:"千丘之国，治安好"},
"BI":{cn:"布隆迪",en:"Burundi",flag:"🇧🇮",code:"BI",lat:-3.5,lng:29.5,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签"},
"CD":{cn:"刚果金",en:"DR Congo",flag:"🇨🇩",code:"CD",lat:-4,lng:22,policy:"visa",duration:"—",fee:"约500元",process:"需提前办理",validity:"—",requirements:"邀请函",tips:"安全形势需关注"},
"CG":{cn:"刚果布",en:"Republic of Congo",flag:"🇨🇬",code:"CG",lat:-1,lng:15,policy:"visa",duration:"—",fee:"约400元",process:"需提前办理",validity:"—",requirements:"护照",tips:"签证可办"},
"GA":{cn:"加蓬",en:"Gabon",flag:"🇬🇦",code:"GA",lat:-0.5,lng:11.5,policy:"evisa",duration:"90天",fee:"约500元",process:"3工作日",validity:"90天",requirements:"护照、网上申请",tips:"电子签"},
"CM":{cn:"喀麦隆",en:"Cameroon",flag:"🇨🇲",code:"CM",lat:6,lng:12,policy:"evisa",duration:"30天",fee:"约500元",process:"电子签2-5天",validity:"30天",requirements:"护照、照片、网上申请",tips:"电子签可办，需小黄本"},
"CF":{cn:"中非",en:"Central African Republic",flag:"🇨🇫",code:"CF",lat:6.5,lng:21,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"—",tips:"安全形势不稳定"},
"TD":{cn:"乍得",en:"Chad",flag:"🇹🇩",code:"TD",lat:15,lng:19,policy:"visa",duration:"—",fee:"约400元",process:"需提前办理",validity:"—",requirements:"护照",tips:"签证较难"},
"NE":{cn:"尼日尔",en:"Niger",flag:"🇳🇪",code:"NE",lat:16,lng:8,policy:"visa",duration:"—",fee:"约300元",process:"需提前办理",validity:"—",requirements:"护照",tips:"安全形势需关注"},
"NG":{cn:"尼日利亚",en:"Nigeria",flag:"🇳🇬",code:"NG",lat:10,lng:8,policy:"visa",duration:"—",fee:"约800元",process:"电子签3-5天",validity:"90天",requirements:"护照、邀请函、黄热病疫苗证明",tips:"非洲人口最多，电子签可办，需小黄本"},
"GH":{cn:"加纳",en:"Ghana",flag:"🇬🇭",code:"GH",lat:8,lng:-1.2,policy:"visa",duration:"—",fee:"约300元",process:"需提前办理",validity:"30天",requirements:"护照",tips:"签证可办"},
"CI":{cn:"科特迪瓦",en:"Ivory Coast",flag:"🇨🇮",code:"CI",lat:7,lng:-5,policy:"evisa",duration:"30天",fee:"约500元",process:"2工作日",validity:"30天",requirements:"护照、网上申请",tips:"电子签"},
"SN":{cn:"塞内加尔",en:"Senegal",flag:"🇸🇳",code:"SN",lat:14,lng:-14,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"免签！达喀尔是西非门户"},
"ML":{cn:"马里",en:"Mali",flag:"🇲🇱",code:"ML",lat:17,lng:-4,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"安全形势不稳定"},
"BF":{cn:"布基纳法索",en:"Burkina Faso",flag:"🇧🇫",code:"BF",lat:12,lng:-1.5,policy:"visa",duration:"—",fee:"约400元",process:"需提前办理",validity:"—",requirements:"护照",tips:"安全形势需关注"},
"GN":{cn:"几内亚",en:"Guinea",flag:"🇬🇳",code:"GN",lat:10.5,lng:-10,policy:"evisa",duration:"—",fee:"约300元",process:"电子签",validity:"90天",requirements:"护照、网上申请",tips:"电子签可办"},
"GW":{cn:"几内亚比绍",en:"Guinea-Bissau",flag:"🇬🇼",code:"GW",lat:12,lng:-15,policy:"arrival",duration:"90天",fee:"约500元",process:"到达办理",validity:"90天",requirements:"护照",tips:"落地签"},
"SL":{cn:"塞拉利昂",en:"Sierra Leone",flag:"🇸🇱",code:"SL",lat:8.5,lng:-11.8,policy:"arrival",duration:"30天",fee:"约500元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签"},
"LR":{cn:"利比里亚",en:"Liberia",flag:"🇱🇷",code:"LR",lat:6.5,lng:-9.5,policy:"visa",duration:"—",fee:"约400元",process:"需提前办理",validity:"—",requirements:"护照",tips:"签证较复杂"},
"GM":{cn:"冈比亚",en:"Gambia",flag:"🇬🇲",code:"GM",lat:13.5,lng:-15,policy:"arrival",duration:"—",fee:"免费",process:"到达办理",validity:"—",requirements:"护照",tips:"西非小国，到达免费"},
"BJ":{cn:"贝宁",en:"Benin",flag:"🇧🇯",code:"BJ",lat:9.5,lng:2.2,policy:"arrival",duration:"30天",fee:"约300元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签，伏都教发源地"},
"TG":{cn:"多哥",en:"Togo",flag:"🇹🇬",code:"TG",lat:8,lng:1.2,policy:"arrival",duration:"7天",fee:"免费",process:"到达办理",validity:"7天",requirements:"护照",tips:"落地签7天免费"},
"CV":{cn:"佛得角",en:"Cape Verde",flag:"🇨🇻",code:"CV",lat:16,lng:-24,policy:"arrival",duration:"30天",fee:"约200元",process:"到达办理",validity:"30天",requirements:"护照",tips:"大西洋岛国"},
"MR":{cn:"毛里塔尼亚",en:"Mauritania",flag:"🇲🇷",code:"MR",lat:20,lng:-10,policy:"arrival",duration:"30天",fee:"约300元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签"},
"GQ":{cn:"赤道几内亚",en:"Equatorial Guinea",flag:"🇬🇶",code:"GQ",lat:1.5,lng:10,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"邀请函",tips:"签证较难"},
"ST":{cn:"圣多美",en:"Sao Tome and Principe",flag:"🇸🇹",code:"ST",lat:0.3,lng:6.6,policy:"arrival",duration:"15天",fee:"约200元",process:"到达办理",validity:"15天",requirements:"护照",tips:"西非小岛国"},
"AO":{cn:"安哥拉",en:"Angola",flag:"🇦🇴",code:"AO",lat:-12,lng:18,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"免签！近年开放旅游"},
"ZM":{cn:"赞比亚",en:"Zambia",flag:"🇿🇲",code:"ZM",lat:-15,lng:28,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"免签！维多利亚瀑布"},
"ZW":{cn:"津巴布韦",en:"Zimbabwe",flag:"🇿🇼",code:"ZW",lat:-20,lng:30,policy:"arrival",duration:"30天",fee:"约350元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签"},
"MZ":{cn:"莫桑比克",en:"Mozambique",flag:"🇲🇿",code:"MZ",lat:-18,lng:35,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"免签！海岸线长"},
"MG":{cn:"马达加斯加",en:"Madagascar",flag:"🇲🇬",code:"MG",lat:-19,lng:47,policy:"arrival",duration:"90天",fee:"约200元",process:"到达办理",validity:"90天",requirements:"护照",tips:"狐猴和猴面包树大道"},
"MU":{cn:"毛里求斯",en:"Mauritius",flag:"🇲🇺",code:"MU",lat:-20,lng:57.5,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！印度洋度假天堂"},
"SC":{cn:"塞舌尔",en:"Seychelles",flag:"🇸🇨",code:"SC",lat:-4.7,lng:55.5,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！顶级海岛"},
"KM":{cn:"科摩罗",en:"Comoros",flag:"🇰🇲",code:"KM",lat:-12,lng:44,policy:"arrival",duration:"45天",fee:"约200元",process:"到达办理",validity:"45天",requirements:"护照",tips:"落地签"},
"NA":{cn:"纳米比亚",en:"Namibia",flag:"🇳🇦",code:"NA",lat:-22,lng:17,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"签证可办"},
"BW":{cn:"博茨瓦纳",en:"Botswana",flag:"🇧🇼",code:"BW",lat:-22,lng:24,policy:"arrival",duration:"90天",fee:"约700元",process:"到达办理",validity:"90天",requirements:"护照",tips:"奥卡万戈三角洲"},
"ZA":{cn:"南非",en:"South Africa",flag:"🇿🇦",code:"ZA",lat:-29,lng:24,policy:"visa",duration:"—",fee:"约200元",process:"5-10工作日",validity:"30天/90天",requirements:"护照、照片、在职证明",tips:"开普敦必去"},
"SZ":{cn:"斯威士兰",en:"Eswatini",flag:"🇸🇿",code:"SZ",lat:-26.5,lng:31.5,policy:"evisa",duration:"30天",fee:"约200元",process:"电子签",validity:"30天",requirements:"护照",tips:"电子签可办"},
"LS":{cn:"莱索托",en:"Lesotho",flag:"🇱🇸",code:"LS",lat:-29.5,lng:28,policy:"visa",duration:"—",fee:"约200元",process:"需提前办理",validity:"—",requirements:"护照",tips:"国中之国"},
"MW":{cn:"马拉维",en:"Malawi",flag:"🇲🇼",code:"MW",lat:-13.5,lng:34,policy:"arrival",duration:"30天",fee:"约350元",process:"到达办理",validity:"30天",requirements:"护照",tips:"落地签"},
"US":{cn:"美国",en:"United States",flag:"🇺🇸",code:"US",lat:38,lng:-97,policy:"visa",duration:"—",fee:"约1100元",process:"面签后5-7天",validity:"10年多次",requirements:"DS-160、面签、在职证明、银行流水",tips:"有美签可解锁很多国家"},
"CA":{cn:"加拿大",en:"Canada",flag:"🇨🇦",code:"CA",lat:56,lng:-106,policy:"visa",duration:"—",fee:"约700元",process:"10-15工作日",validity:"多次",requirements:"护照、照片、在职证明、银行流水",tips:"有美签可简化"},
"MX":{cn:"墨西哥",en:"Mexico",flag:"🇲🇽",code:"MX",lat:23,lng:-102,policy:"visa",duration:"—",fee:"约280元",process:"约10工作日",validity:"按行程",requirements:"护照、照片、银行流水",tips:"持美签/加签/申根签可免签"},
"GT":{cn:"危地马拉",en:"Guatemala",flag:"🇬🇹",code:"GT",lat:15.5,lng:-90.2,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/申根签可免签",tips:"需第三国签证"},
"HN":{cn:"洪都拉斯",en:"Honduras",flag:"🇭🇳",code:"HN",lat:15,lng:-87,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/申根签可免签",tips:"需第三国签证"},
"SV":{cn:"萨尔瓦多",en:"El Salvador",flag:"🇸🇻",code:"SV",lat:13.8,lng:-88.9,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签可免签",tips:"需美签"},
"NI":{cn:"尼加拉瓜",en:"Nicaragua",flag:"🇳🇮",code:"NI",lat:12.9,lng:-85,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签可免签",tips:"需美签"},
"CR":{cn:"哥斯达黎加",en:"Costa Rica",flag:"🇨🇷",code:"CR",lat:10,lng:-84,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/加签/申根签可免签",tips:"中美洲最安全"},
"PA":{cn:"巴拿马",en:"Panama",flag:"🇵🇦",code:"PA",lat:9,lng:-80,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签可免签",tips:"需美签"},
"CU":{cn:"古巴",en:"Cuba",flag:"🇨🇺",code:"CU",lat:22,lng:-80,policy:"arrival",duration:"30天",fee:"约150元",process:"到达办理",validity:"30天",requirements:"护照、旅游卡",tips:"旅游卡机场购买"},
"DO":{cn:"多米尼加",en:"Dominican Republic",flag:"🇩🇴",code:"DO",lat:19,lng:-70,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/申根签/加签可免签",tips:"需第三国签证"},
"BB":{cn:"巴巴多斯",en:"Barbados",flag:"🇧🇧",code:"BB",lat:13.1,lng:-59.6,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！"},
"AG":{cn:"安提瓜和巴布达",en:"Antigua and Barbuda",flag:"🇦🇬",code:"AG",lat:17,lng:-61.8,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证"},
"DM":{cn:"多米尼克",en:"Dominica",flag:"🇩🇲",code:"DM",lat:15.4,lng:-61.4,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证"},
"GD":{cn:"格林纳达",en:"Grenada",flag:"🇬🇩",code:"GD",lat:12.1,lng:-61.7,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证"},
"BS":{cn:"巴哈马",en:"Bahamas",flag:"🇧🇸",code:"BS",lat:25,lng:-77.4,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！加勒比度假天堂"},
"BR":{cn:"巴西",en:"Brazil",flag:"🇧🇷",code:"BR",lat:-14,lng:-51,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"至2026.12.31",requirements:"护照、往返机票、酒店预订",tips:"限时免签至2026.12.31！里约+伊瓜苏"},
"AR":{cn:"阿根廷",en:"Argentina",flag:"🇦🇷",code:"AR",lat:-38,lng:-64,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签可免签",tips:"持美签可免签"},
"CL":{cn:"智利",en:"Chile",flag:"🇨🇱",code:"CL",lat:-35,lng:-71,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/加签/申根签可免签",tips:"需有效签证"},
"PE":{cn:"秘鲁",en:"Peru",flag:"🇵🇪",code:"PE",lat:-10,lng:-76,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/加签/申根签/澳签可免签",tips:"马丘比丘必去"},
"CO":{cn:"哥伦比亚",en:"Colombia",flag:"🇨🇴",code:"CO",lat:4,lng:-72,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签/申根签可免签",tips:"需有效签证"},
"VE":{cn:"委内瑞拉",en:"Venezuela",flag:"🇻🇪",code:"VE",lat:7,lng:-66,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"—",tips:"局势不稳定"},
"EC":{cn:"厄瓜多尔",en:"Ecuador",flag:"🇪🇨",code:"EC",lat:-1.8,lng:-78,policy:"free",duration:"90天",fee:"免费",process:"—",validity:"90天",requirements:"护照",tips:"互免签证！南美最方便入口"},
"BO":{cn:"玻利维亚",en:"Bolivia",flag:"🇧🇴",code:"BO",lat:-17,lng:-65,policy:"arrival",duration:"90天",fee:"约600元",process:"到达办理",validity:"90天",requirements:"护照、照片、黄热病疫苗证明",tips:"落地签！天空之镜"},
"PY":{cn:"巴拉圭",en:"Paraguay",flag:"🇵🇾",code:"PY",lat:-23,lng:-58,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"南美内陆国"},
"UY":{cn:"乌拉圭",en:"Uruguay",flag:"🇺🇾",code:"UY",lat:-33,lng:-56,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"持有效美签可免签",tips:"需美签"},
"GY":{cn:"圭亚那",en:"Guyana",flag:"🇬🇾",code:"GY",lat:5,lng:-59,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"南美北部"},
"SR":{cn:"苏里南",en:"Suriname",flag:"🇸🇷",code:"SR",lat:4,lng:-56,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！"},
"HT":{cn:"海地",en:"Haiti",flag:"🇭🇹",code:"HT",lat:19,lng:-72,policy:"arrival",duration:"90天",fee:"免费",process:"到达办理",validity:"90天",requirements:"护照",tips:"局势不稳定"},
"BZ":{cn:"伯利兹",en:"Belize",flag:"🇧🇿",code:"BZ",lat:17.3,lng:-88.5,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"需美签",tips:"中美洲小国"},
"JM":{cn:"牙买加",en:"Jamaica",flag:"🇯🇲",code:"JM",lat:18,lng:-77,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"持有效美签可免签",tips:"持美签可免签"},
"TT":{cn:"特立尼达和多巴哥",en:"Trinidad and Tobago",flag:"🇹🇹",code:"TT",lat:10.5,lng:-61,policy:"visa",duration:"—",fee:"—",process:"需提前办理",validity:"—",requirements:"需签证",tips:"加勒比海国家"},
"KN":{cn:"圣基茨和尼维斯",en:"Saint Kitts and Nevis",flag:"🇰🇳",code:"KN",lat:17.3,lng:-62.7,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"加勒比小国"},
"LC":{cn:"圣卢西亚",en:"Saint Lucia",flag:"🇱🇨",code:"LC",lat:13.9,lng:-61,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"加勒比小国"},
"VC":{cn:"圣文森特",en:"Saint Vincent and the Grenadines",flag:"🇻🇨",code:"VC",lat:13.2,lng:-61.2,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"加勒比小国"},
"AU":{cn:"澳大利亚",en:"Australia",flag:"🇦🇺",code:"AU",lat:-25,lng:134,policy:"visa",duration:"—",fee:"约750元",process:"10-20工作日",validity:"1年多次",requirements:"护照、照片、在职证明、银行流水",tips:"有澳签可解锁太平洋岛国"},
"NZ":{cn:"新西兰",en:"New Zealand",flag:"🇳🇿",code:"NZ",lat:-41,lng:174,policy:"visa",duration:"—",fee:"约1100元",process:"15-25工作日",validity:"多次",requirements:"护照、照片、在职证明、银行流水",tips:"自然风光绝美"},
"FJ":{cn:"斐济",en:"Fiji",flag:"🇫🇯",code:"FJ",lat:-18,lng:178,policy:"free",duration:"120天",fee:"免费",process:"—",validity:"120天",requirements:"护照",tips:"互免签证！可从香港直飞"},
"PG":{cn:"巴布亚新几内亚",en:"Papua New Guinea",flag:"🇵🇬",code:"PG",lat:-6,lng:147,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"旅游不太方便"},
"SB":{cn:"所罗门群岛",en:"Solomon Islands",flag:"🇸🇧",code:"SB",lat:-9,lng:160,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！"},
"VU":{cn:"瓦努阿图",en:"Vanuatu",flag:"🇻🇺",code:"VU",lat:-16,lng:167,policy:"free",duration:"120天",fee:"免费",process:"—",validity:"120天",requirements:"护照",tips:"互免签证！活火山"},
"TO":{cn:"汤加",en:"Tonga",flag:"🇹🇴",code:"TO",lat:-21,lng:-175,policy:"free",duration:"30天",fee:"免费",process:"—",validity:"30天",requirements:"护照",tips:"互免签证！"},
"WS":{cn:"萨摩亚",en:"Samoa",flag:"🇼🇸",code:"WS",lat:-13.5,lng:-172,policy:"free",duration:"60天",fee:"免费",process:"—",validity:"60天",requirements:"护照",tips:"互免签证！"},
"PW":{cn:"帕劳",en:"Palau",flag:"🇵🇼",code:"PW",lat:7.5,lng:134.5,policy:"arrival",duration:"30天",fee:"免费",process:"到达办理",validity:"30天",requirements:"护照、往返机票",tips:"潜水天堂"},
"TV":{cn:"图瓦卢",en:"Tuvalu",flag:"🇹🇻",code:"TV",lat:-7.1,lng:179.2,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需从斐济转机",tips:"世界第四小国"},
"KI":{cn:"基里巴斯",en:"Kiribati",flag:"🇰🇮",code:"KI",lat:1.9,lng:-157,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"太平洋岛国"},
"NR":{cn:"瑙鲁",en:"Nauru",flag:"🇳🇷",code:"NR",lat:-0.5,lng:166.9,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"世界第三小国"},
"FM":{cn:"密克罗尼西亚",en:"Micronesia",flag:"🇫🇲",code:"FM",lat:7,lng:151,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"太平洋岛国"},
"MH":{cn:"马绍尔群岛",en:"Marshall Islands",flag:"🇲🇭",code:"MH",lat:9,lng:168,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"需签证",tips:"太平洋岛国"},
"PS":{cn:"巴勒斯坦",en:"Palestine",flag:"🇵🇸",code:"PS",lat:31.9,lng:35.2,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"通过以色列或埃及进入",tips:"无独立边境"},
"AQ":{cn:"南极洲",en:"Antarctica",flag:"🇦🇶",code:"AQ",lat:-82,lng:0,policy:"none",duration:"—",fee:"—",process:"—",validity:"—",requirements:"无需签证",tips:"需从阿根廷/智利出发"},
"TW":{cn:"台湾",en:"Taiwan",flag:"🇹🇼",code:"TW",lat:23.5,lng:121,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"台胞证",tips:"需台湾通行证+入台证"},
"HK":{cn:"香港",en:"Hong Kong",flag:"🇭🇰",code:"HK",lat:22.3,lng:114.2,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"港澳通行证",tips:"需港澳通行证"},
"MO":{cn:"澳门",en:"Macau",flag:"🇲🇴",code:"MO",lat:22.2,lng:113.5,policy:"visa",duration:"—",fee:"—",process:"—",validity:"—",requirements:"港澳通行证",tips:"需港澳通行证"}
};
console.log("VISA_DATA loaded:", Object.keys(VISA_DATA).length, "countries/territories");
